[versions]
agp = "8.7.3"
androidActivation = "1.6.7"
fragmentKtx = "1.8.5"
gson = "2.11.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
library = "2.1.3"
loggingInterceptor = "4.12.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.0"
playServicesCronet = "18.0.1"
retrofit = "2.11.0"
threetenbp = "1.7.0"
navigationFragment = "2.8.4"
navigationUi = "2.8.4"

[libraries]
android-activation = { module = "com.sun.mail:android-activation", version.ref = "androidActivation" }
android-mail = { module = "com.sun.mail:android-mail", version.ref = "androidActivation" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
library = { module = "com.wang.avi:library", version.ref = "library" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
play-services-cronet = { module = "com.google.android.gms:play-services-cronet", version.ref = "playServicesCronet" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
threetenbp = { module = "org.threeten:threetenbp", version.ref = "threetenbp" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

